Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 240

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Max: 1500

Metrics/BlockLength:
  Enabled: false

AbcSize:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: "inject"

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/NegatedIf:
  Enabled: false
