Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Style/SymbolArray:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: "inject"

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Style/Documentation:
  Enabled: false
