#!/bin/zsh

function main () {
    local stashes=($(read_and_format))

    if [ -z "${stashes}" ]
    then
        return
    fi

    printf "${(j/, /)stashes}"
}

function read_and_format () {
    read_stashes | format_stash
}

function read_stashes () {
    git stash list --format='%gd %s' 2>/dev/null
}

function format_stash () {
    awk '
    {
        if (/^stash@{[0-9]+} WIP/) {
            sub(/stash@/, "", $1);
            print $1
        } else {
            split($0, array, ": ");
            print array[2]
        }
    }'
}

main
