-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [1] = "run:transmission-gtk",
    [2] = "run:firefox",
    [3] = "run:virtualbox",
    [4] = "run:transmission-gt",
    [5] = "run:transmission-cli",
    [6] = "menu.ctxmenu:",
    [7] = "run:gimp-2.8",
    [8] = "run:unity-tweak-tool",
    [9] = "run:unity-control-center",
    [10] = "windowname:amEebayasdasdasdasdasd",
    [11] = "menu.mainmenu:session/exit",
    [12] = "run:xterm",
    [13] = "run:gnome-terminal",
    [14] = "menu.mainmenu:session/restart",
    [15] = "run:chrome",
    [16] = "run:pavucontrol",
    [17] = "run:firefo",
}

