-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [0] = {
        ["managed"] = {
            [1] = {
                ["sizepolicy"] = "full",
                ["switchto"] = true,
                ["name"] = "WGroupWS<1>",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<1>",
                        ["type"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1800,
                            ["w"] = 2880,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                            [1] = {
                                                ["sizepolicy"] = "full",
                                                ["name"] = "WGroupCW<15>",
                                                ["type"] = "WGroupCW",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["sizepolicy"] = "full",
                                                        ["bottom"] = true,
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 31459088,
                                                        ["geom"] = {
                                                            ["h"] = 1768,
                                                            ["w"] = 1492,
                                                            ["x"] = 0,
                                                            ["y"] = 0,
                                                        },
                                                        ["checkcode"] = 1,
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["hidden"] = true,
                                                ["geom"] = {
                                                    ["h"] = 1768,
                                                    ["w"] = 1492,
                                                    ["x"] = 1,
                                                    ["y"] = 15,
                                                },
                                                ["level"] = 0,
                                            },
                                            [2] = {
                                                ["sizepolicy"] = "full",
                                                ["name"] = "WGroupCW<17>",
                                                ["type"] = "WGroupCW",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["sizepolicy"] = "full",
                                                        ["bottom"] = true,
                                                        ["type"] = "WClientWin",
                                                        ["windowid"] = 31458599,
                                                        ["geom"] = {
                                                            ["h"] = 1768,
                                                            ["w"] = 1492,
                                                            ["x"] = 0,
                                                            ["y"] = 0,
                                                        },
                                                        ["checkcode"] = 2,
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                                ["geom"] = {
                                                    ["h"] = 1768,
                                                    ["w"] = 1492,
                                                    ["x"] = 1,
                                                    ["y"] = 15,
                                                },
                                                ["switchto"] = true,
                                            },
                                        },
                                        ["mode"] = 1,
                                        ["name"] = "Tiling Frame<2>",
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                                ["brs"] = 1386,
                                ["tls"] = 1494,
                                ["br"] = {
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["name"] = "WGroupCW<5>",
                                                    ["type"] = "WGroupCW",
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["sizepolicy"] = "full",
                                                            ["bottom"] = true,
                                                            ["type"] = "WClientWin",
                                                            ["windowid"] = 31458589,
                                                            ["geom"] = {
                                                                ["h"] = 1296,
                                                                ["w"] = 1384,
                                                                ["x"] = 0,
                                                                ["y"] = 0,
                                                            },
                                                            ["checkcode"] = 3,
                                                            ["level"] = 1,
                                                        },
                                                    },
                                                    ["hidden"] = true,
                                                    ["geom"] = {
                                                        ["h"] = 1296,
                                                        ["w"] = 1384,
                                                        ["x"] = 1,
                                                        ["y"] = 15,
                                                    },
                                                    ["level"] = 0,
                                                },
                                                [2] = {
                                                    ["sizepolicy"] = "full",
                                                    ["name"] = "WGroupCW<9>",
                                                    ["type"] = "WGroupCW",
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["sizepolicy"] = "full",
                                                            ["bottom"] = true,
                                                            ["type"] = "WClientWin",
                                                            ["windowid"] = 48327406,
                                                            ["geom"] = {
                                                                ["h"] = 1292,
                                                                ["w"] = 1379,
                                                                ["x"] = 3,
                                                                ["y"] = 2,
                                                            },
                                                            ["checkcode"] = 4,
                                                            ["level"] = 1,
                                                        },
                                                    },
                                                    ["level"] = 0,
                                                    ["geom"] = {
                                                        ["h"] = 1296,
                                                        ["w"] = 1384,
                                                        ["x"] = 1,
                                                        ["y"] = 15,
                                                    },
                                                    ["switchto"] = true,
                                                },
                                            },
                                            ["mode"] = 1,
                                            ["name"] = "Tiling Frame<3>",
                                            ["type"] = "WFrame",
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["type"] = "WSplitSplit",
                                    ["brs"] = 472,
                                    ["tls"] = 1312,
                                    ["br"] = {
                                        ["regparams"] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["name"] = "WGroupCW<8>",
                                                    ["type"] = "WGroupCW",
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["sizepolicy"] = "full",
                                                            ["bottom"] = true,
                                                            ["type"] = "WClientWin",
                                                            ["windowid"] = 48234502,
                                                            ["geom"] = {
                                                                ["h"] = 467,
                                                                ["w"] = 1379,
                                                                ["x"] = 3,
                                                                ["y"] = 2,
                                                            },
                                                            ["checkcode"] = 5,
                                                            ["level"] = 1,
                                                        },
                                                    },
                                                    ["level"] = 0,
                                                    ["geom"] = {
                                                        ["h"] = 470,
                                                        ["w"] = 1384,
                                                        ["x"] = 1,
                                                        ["y"] = 1,
                                                    },
                                                    ["switchto"] = true,
                                                },
                                            },
                                            ["mode"] = 2,
                                            ["name"] = "Tiling Frame",
                                            ["type"] = "WFrame",
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["dir"] = "vertical",
                                },
                                ["dir"] = "horizontal",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,
                            ["tls"] = 1784,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["level"] = 0,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "DP1",
                },
            },
            [2] = {
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["name"] = "WGroupWS<9>",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<9>",
                        ["type"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1800,
                            ["w"] = 2880,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<2>",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 31457287,
                                                    ["geom"] = {
                                                        ["h"] = 1768,
                                                        ["w"] = 2878,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 6,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["h"] = 1768,
                                                ["w"] = 2878,
                                                ["x"] = 1,
                                                ["y"] = 15,
                                            },
                                            ["level"] = 0,
                                        },
                                        [2] = {
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<3>",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 31457288,
                                                    ["geom"] = {
                                                        ["h"] = 1768,
                                                        ["w"] = 2878,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 7,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["h"] = 1768,
                                                ["w"] = 2878,
                                                ["x"] = 1,
                                                ["y"] = 15,
                                            },
                                            ["level"] = 0,
                                        },
                                        [3] = {
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<12>",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 31458858,
                                                    ["geom"] = {
                                                        ["h"] = 1768,
                                                        ["w"] = 2878,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 8,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["h"] = 1768,
                                                ["w"] = 2878,
                                                ["x"] = 1,
                                                ["y"] = 15,
                                            },
                                            ["level"] = 0,
                                        },
                                        [4] = {
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<4>",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 31457289,
                                                    ["geom"] = {
                                                        ["h"] = 1768,
                                                        ["w"] = 2878,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 9,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["h"] = 1768,
                                                ["w"] = 2878,
                                                ["x"] = 1,
                                                ["y"] = 15,
                                            },
                                            ["level"] = 0,
                                        },
                                        [5] = {
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<6>",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 31457291,
                                                    ["geom"] = {
                                                        ["h"] = 1768,
                                                        ["w"] = 2878,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 10,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["h"] = 1768,
                                                ["w"] = 2878,
                                                ["x"] = 1,
                                                ["y"] = 15,
                                            },
                                            ["level"] = 0,
                                        },
                                        [6] = {
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 31457281,
                                                    ["geom"] = {
                                                        ["h"] = 1768,
                                                        ["w"] = 2878,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 11,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                            ["geom"] = {
                                                ["h"] = 1768,
                                                ["w"] = 2878,
                                                ["x"] = 1,
                                                ["y"] = 15,
                                            },
                                            ["switchto"] = true,
                                        },
                                    },
                                    ["mode"] = 1,
                                    ["name"] = "WFrame<12>",
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,
                            ["tls"] = 1784,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "DP1",
                },
            },
            [3] = {
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["name"] = "WGroupWS<16>",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<16>",
                        ["type"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1800,
                            ["w"] = 2880,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<11>",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 31457765,
                                                    ["geom"] = {
                                                        ["h"] = 1782,
                                                        ["w"] = 2878,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 12,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                            ["geom"] = {
                                                ["h"] = 1782,
                                                ["w"] = 2878,
                                                ["x"] = 1,
                                                ["y"] = 1,
                                            },
                                            ["switchto"] = true,
                                        },
                                    },
                                    ["mode"] = 2,
                                    ["name"] = "WFrame<4>",
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,
                            ["tls"] = 1784,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
            },
            [4] = {
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["name"] = "WGroupWS<2>",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<2>",
                        ["type"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1800,
                            ["w"] = 2880,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<7>",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 31458700,
                                                    ["geom"] = {
                                                        ["h"] = 1768,
                                                        ["w"] = 2878,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 13,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["h"] = 1768,
                                                ["w"] = 2878,
                                                ["x"] = 1,
                                                ["y"] = 15,
                                            },
                                            ["level"] = 0,
                                        },
                                        [2] = {
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<1>",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 31457723,
                                                    ["geom"] = {
                                                        ["h"] = 1768,
                                                        ["w"] = 2878,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 14,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["geom"] = {
                                                ["h"] = 1768,
                                                ["w"] = 2878,
                                                ["x"] = 1,
                                                ["y"] = 15,
                                            },
                                            ["level"] = 0,
                                        },
                                        [3] = {
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<14>",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 31458284,
                                                    ["geom"] = {
                                                        ["h"] = 1768,
                                                        ["w"] = 2878,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 15,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                            ["geom"] = {
                                                ["h"] = 1768,
                                                ["w"] = 2878,
                                                ["x"] = 1,
                                                ["y"] = 15,
                                            },
                                            ["switchto"] = true,
                                        },
                                    },
                                    ["mode"] = 1,
                                    ["name"] = "WFrame<1>",
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,
                            ["tls"] = 1784,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
            },
            [5] = {
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["name"] = "WGroupWS<19>",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<19>",
                        ["type"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1800,
                            ["w"] = 2880,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<10>",
                                            ["type"] = "WGroupCW",
                                            ["managed"] = {
                                                [1] = {
                                                    ["sizepolicy"] = "full",
                                                    ["bottom"] = true,
                                                    ["type"] = "WClientWin",
                                                    ["windowid"] = 44040199,
                                                    ["geom"] = {
                                                        ["h"] = 1782,
                                                        ["w"] = 2878,
                                                        ["x"] = 0,
                                                        ["y"] = 0,
                                                    },
                                                    ["checkcode"] = 16,
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                            ["geom"] = {
                                                ["h"] = 1782,
                                                ["w"] = 2878,
                                                ["x"] = 1,
                                                ["y"] = 1,
                                            },
                                            ["switchto"] = true,
                                        },
                                    },
                                    ["mode"] = 2,
                                    ["name"] = "WFrame<30>",
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,
                            ["tls"] = 1784,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
            },
            [6] = {
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["name"] = "WGroupWS",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling",
                        ["type"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1800,
                            ["w"] = 2880,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["mode"] = 1,
                                    ["name"] = "WFrame<14>",
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,
                            ["tls"] = 1784,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
            },
            [7] = {
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["name"] = "WGroupWS<20>",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<20>",
                        ["type"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1800,
                            ["w"] = 2880,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["mode"] = 1,
                                        ["name"] = "WFrame<33>",
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                                ["brs"] = 1440,
                                ["tls"] = 1440,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["mode"] = 1,
                                        ["name"] = "WFrame<34>",
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "horizontal",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,
                            ["tls"] = 1784,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
            },
            [8] = {
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["name"] = "WGroupWS<21>",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<21>",
                        ["type"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1800,
                            ["w"] = 2880,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["mode"] = 1,
                                        ["name"] = "WFrame<35>",
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                                ["brs"] = 1440,
                                ["tls"] = 1440,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["mode"] = 1,
                                        ["name"] = "WFrame<36>",
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "horizontal",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,
                            ["tls"] = 1784,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
            },
            [9] = {
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["name"] = "WGroupWS<22>",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<22>",
                        ["type"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1800,
                            ["w"] = 2880,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["mode"] = 1,
                                        ["name"] = "WFrame<37>",
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                                ["brs"] = 1440,
                                ["tls"] = 1440,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["mode"] = 1,
                                        ["name"] = "WFrame<38>",
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "horizontal",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,
                            ["tls"] = 1784,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP1",
                },
            },
            [10] = {
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["name"] = "WGroupWS<3>",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<3>",
                        ["type"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1800,
                            ["w"] = 2880,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["mode"] = 1,
                                        ["name"] = "WFrame<2>",
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                                ["brs"] = 1440,
                                ["tls"] = 1440,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                        },
                                        ["mode"] = 1,
                                        ["name"] = "WFrame<10>",
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "horizontal",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,
                            ["tls"] = 1784,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP-1",
                },
            },
            [11] = {
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["name"] = "WGroupWS<10>",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<10>",
                        ["type"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                        ["geom"] = {
                            ["h"] = 1800,
                            ["w"] = 2880,
                            ["x"] = 0,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["mode"] = 2,
                                    ["name"] = "WFrame<3>",
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                            ["brs"] = 16,
                            ["tls"] = 1784,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                        },
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "eDP-1",
                },
            },
            [12] = {
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["sizepolicy"] = "free_glue",
                        ["bottom"] = true,
                        ["name"] = "*scratchpad*",
                        ["type"] = "WFrame",
                        ["managed"] = {
                        },
                        ["mode"] = 0,
                        ["geom"] = {
                            ["h"] = 480,
                            ["w"] = 640,
                            ["x"] = 1120,
                            ["y"] = 660,
                        },
                        ["level"] = 1025,
                    },
                },
                ["hidden"] = true,
                ["geom"] = {
                    ["h"] = 1800,
                    ["w"] = 2880,
                    ["x"] = 0,
                    ["y"] = 0,
                },
                ["pseudomodal"] = true,
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["level"] = 1,
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
            },
        },
        ["name"] = "WScreen",
        ["type"] = "WScreen",
    },
}

