#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc keyunbind --all

# settings
hc set focus_follows_mouse 1
hc set always_show_frame 1
hc set tree_style '╾│ ├└╼─┐'
# 2 = max layout
hc set default_frame_layout 2

# keyboard setup
Mod=Mod4

# basic 
hc keybind $Mod-Shift-q   quit
hc keybind $Mod-Shift-r   reload
hc keybind $Mod-c         close_or_remove
hc keybind $Mod-Tab       cycle +1
hc keybind $Mod-Shift-Tab cycle -1
hc keybind $Mod-n         cycle_frame +1
hc keybind $Mod-p         cycle_frame -1
hc keybind $Mod-Return    fullscreen toggle
hc keybind $Mod-space     cycle_layout 1
hc keybind $Mod-period    use_index +1 --skip-visible
hc keybind $Mod-comma     use_index -1 --skip-visible

# run stuff 
hc keybind $Mod-F2 spawn gnome-terminal
hc keybind $Mod-F3 spawn dmenu_run -nb '#000' -nf '#fff' -sb '#f00' -sf '#fff' -fn 'DejaVu Sans-10:ExtraLight'
hc keybind $Mod-F4 spawn google-chrome

# media keys
hc keybind XF86AudioMute        spawn $HOME/.zsh/robs/bin/volume mute
hc keybind XF86AudioRaiseVolume spawn $HOME/.zsh/robs/bin/volume up
hc keybind XF86AudioLowerVolume spawn $HOME/.zsh/robs/bin/volume down

# set layout
hc keybind $Mod-m set_layout max
hc keybind $Mod-| set_layout vertical
hc keybind $Mod-- set_layout horizontal 
hc keybind $Mod-g set_layout grid

# splitting frames
hc keybind $Mod-h       chain . split top     0.5 . set_layout max
hc keybind $Mod-v       chain . split left    0.5 . set_layout max
hc keybind $Mod-Shift-h chain . split bottom  0.5 . set_layout max
hc keybind $Mod-Shift-v chain . split right   0.5 . set_layout max

# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-Left    resize left  +$resizestep
hc keybind $Mod-Control-Down    resize down  +$resizestep
hc keybind $Mod-Control-Up      resize up    +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags (virtual desktops)
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true

for i in ${!tag_names[@]} ; do

    hc add "${tag_names[$i]}"

    key="${tag_keys[$i]}"

    if ! [ -z "$key" ] ; then
        # switch desktop
        hc keybind "$Mod-$key" use_index "$i"

        # move window to desktop
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#cccccc'
hc set frame_border_normal_color '#000000'
hc set frame_bg_normal_color '#000000'
hc set frame_bg_active_color '#111111'
hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent 0
hc set frame_gap 0

hc attr theme.active.color '#dddddd'
hc attr theme.normal.color '#333333'
hc attr theme.urgent.color '#ff4444'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color black
hc attr theme.active.outer_color black
hc attr theme.background_color '#000000'

hc set window_gap 3
hc set frame_padding -1
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

# detect monitor resolution
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh

[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh

# start it on each monitor
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    "$panel" $monitor &
done

sleep 0.5

if which stalonetray > /dev/null 2>&1; then
    killall stalonetray; stalonetray -i 16 --background '#101010' --icon-gravity W --grow-gravity E --geometry 1-150 &
    killall nm-applet;   nm-applet &
fi
