ZSH_ROOT="${HOME}/.zsh"

export TERM=screen-256color
export PATH="/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin"

autoload -U compinit && compinit

source ${ZSH_ROOT}/spectrum.zsh
source ${ZSH_ROOT}/vi-mode/vi-mode.plugin.zsh
source ${ZSH_ROOT}/zsh-autoenv/init.zsh

for f in ${ZSH_ROOT}/robs/**/*.zsh; do
  source $f
done

# reload bookmarks
b > /dev/null 2>&1
