# stuff to research: auto-fu.sh  zsh-fuzzy-match  zsh-history-substring-search

# stop here if not a shell
if [ ! -n "$PS1" ]; then return; fi

# configure some stuff
export LESS="-R" # allow escape sequences to be interpreted properly
export EDITOR="vim"
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;32'

ZSH_ROOT="$HOME/.zsh"

for f in $ZSH_ROOT/**/*.zsh; source $f
