ZSH_ROOT="${HOME}/.zsh"

if [[ -r $HOME/.terminfo/78/xterm-256color-italic ]]; then
  export TERM=xterm-256color-italic
else
  export TERM=xterm-256color
fi
export PATH="$PATH:/usr/local/bin:/usr/local/sbin"

autoload -U compinit && compinit

source ${ZSH_ROOT}/spectrum.zsh

for f in ${ZSH_ROOT}/robs/*.zsh; do
  source $f
done

# reload bookmarks
b > /dev/null 2>&1
