vim.opt.completeopt = "menuone,noinsert" -- better completion
vim.opt.colorcolumn = '80' -- Line length marker
vim.opt.cursorline = false -- Highlight cursor line
vim.opt.expandtab = true -- Use spaces instead of tabs
vim.opt.formatoptions = 'ocqnjv' -- Automatic formatting options, see: help fo-table
vim.opt.autoindent = true -- Set auto-indent, required for numbered listss
vim.opt.hidden = true -- Enable background buffers
vim.opt.ignorecase = true -- Ignore case
vim.opt.joinspaces = false -- No double spaces with join
vim.opt.list = true -- Show some invisible characters
vim.opt.number = false -- Show line numbers
vim.opt.pastetoggle = '<F2>' -- Paste mode
vim.opt.relativenumber = false -- Relative line numbers
vim.opt.scrolloff = 4 -- Lines of context
vim.opt.shiftround = true -- Round indent
vim.opt.shiftwidth = 2 -- Size of an indent
vim.opt.sidescrolloff = 8 -- Columns of context
vim.opt.signcolumn = 'auto' -- Show sign column
vim.opt.smartcase = true -- Do not ignore case with capitals
vim.opt.smartindent = true -- Insert indents automatically
vim.opt.splitbelow = true -- Put new windows below current
vim.opt.splitright = true -- Put new windows right of current
vim.opt.tabstop = 2 -- Number of spaces tabs count for
vim.opt.textwidth = 80 -- Maximum width of text
vim.opt.updatetime = 100 -- Delay before swap file is saved
vim.opt.wildmode = {'list', 'longest'} -- Command-line completion mode
vim.opt.wrap = true -- Enable line wrap
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.iskeyword = "_,@,48-57,192-255" -- added _ as keyword separator
vim.opt.encoding = "utf8"
vim.opt.showmode = false -- disable showing INSERT etc. in prompt
