-- return {
--   "roobert/bufferline-cycle-windowless.nvim",
--   dependencies = {
--     { "akinsho/bufferline.nvim" },
--   },
--   config = function()
--     require("bufferline-cycle-windowless").setup({
--       default_enabled = true,
--     })
--   end,
-- }
return {}
