-- return {
--   "echasnovski/mini.bufremove",
--   keys = {
--     {
--       "<leader>d",
--       function()
--         require("mini.bufremove").delete(0, false)
--       end,
--       desc = "Delete Buffer",
--     },
--     {
--       "<leader>D",
--       function()
--         require("mini.bufremove").delete(0, true)
--       end,
--       desc = "Delete Buffer (Force)",
--     },
--   },
-- }
return {}
