-- prefer fzf to telescope for fuzzy finding stuff
-- unfortunately telescope is too tightly integrated into lazyvim so telescope-fzf-native is a
-- better option
-- return {
--   "ibhagwan/fzf-lua",
--   dependencies = { "nvim-tree/nvim-web-devicons" },
--   config = function()
--     require("fzf-lua").setup({
--       winopts = {
--         preview = {
--           layout = "vertical",
--         },
--       },
--       actions = {
--         files = {
--           ["default"] = require("fzf-lua.actions").file_edit,
--         },
--       },
--     })
--   end,
-- }
return {}
