-- FIXME: re-enable
-- return {
--   "roobert/surround-ui.nvim",
--   dependencies = {
--     "kylechui/nvim-surround",
--     "folke/which-key.nvim",
--   },
--   name = "surround-ui",
--   config = function()
--     require("surround-ui").setup()
--   end,
-- }
return {}
