-- NOTE
-- * See :PackerStatus for loaded plugins..
--
-- Disable some in built plugins completely
local disabled_built_ins = {
    'netrw', 'netrwPlugin', 'netrwSettings', 'netrwFileHandlers', 'gzip', 'zip',
    'zipPlugin', 'tar', 'tarPlugin', -- 'man',
    'getscript', 'getscriptPlugin', 'vimball', 'vimballPlugin', '2html_plugin',
    'logipat', 'rrhelper', 'spellfile_plugin'
    -- 'matchit', 'matchparen', 'shada_plugin',
}

for _, plugin in pairs(disabled_built_ins) do vim.g['loaded_' .. plugin] = 1 end

-- return require('packer').setup(function(use)
--    use {'ray-x/lsp_signature.nvim'}
--
--    -- icons for signatures
--    use {'onsails/lspkind-nvim'}
--
--    -- text objects for paranthesis, brackets, quotes, etc.
--    use {'tpope/vim-surround'}
--
--    -- toggle commenting
--    use {'tpope/vim-commentary'}
--
--    -- more text objects - allow changing values in next object without being
--    -- inside it
--    use {'wellle/targets.vim'}
--
--    -- use '%' to jump between if/end/else, etc.
--    use {'andymass/vim-matchup', event = 'VimEnter'}
--
--    -- Highlight FIXME, TODO, NOTE, etc.
--    use {
--        "folke/todo-comments.nvim",
--        requires = "nvim-lua/plenary.nvim",
--        config = function()
--            require("todo-comments").setup {
--                highlight = {
--                    before = "", -- "fg" or "bg" or empty
--                    keyword = "wide", -- "fg", "bg", "wide" or empty. (wide is the same as bg, but will also highlight surrounding characters)
--                    after = "fg", -- "fg" or "bg" or empty
--                    pattern = [[.*<(KEYWORDS)\s*]], -- pattern used for highlightng (vim regex)
--                    comments_only = true, -- uses treesitter to match keywords in comments only
--                    max_line_len = 400, -- ignore lines longer than this
--                    exclude = {} -- list of file types to exclude highlighting
--                },
--                search = {
--                    command = "rg",
--                    args = {
--                        "--color=never", "--no-heading", "--with-filename",
--                        "--line-number", "--column"
--                    },
--                    pattern = [[\b(KEYWORDS)\b]]
--                }
--            }
--        end
--    }
--
--    -- Nice interface for displaying nvim diagnostics
--    use {
--        "folke/trouble.nvim",
--        requires = "kyazdani42/nvim-web-devicons",
--        config = function() require("trouble").setup {} end
--    }
--
--    -- Old theme
--    use {'roobert/robs.vim'}
--
--    -- Fork of folke/tokyonight..
--    use {'roobert/tokyoshade.nvim'}
--
--    -- Visual-block+enter to align stuff
--    use {'junegunn/vim-easy-align'}
--
--    -- Auto handle ctags to allow jumping to definitions
--    use {'ludovicchabant/vim-gutentags'}
--
--    -- Sidebar to show ctags
--    use {'majutsushi/tagbar'}
--
--    -- Hint about code actions to make them discoverable
--    use {'kosayoda/nvim-lightbulb'}
--
--    -- auto switch between relative and normal line numbers
--    use {'jeffkreeftmeijer/vim-numbertoggle'}
--
--    -- Autopairs but only on CR
--    use {'9mm/vim-closer'}
-- end)
